version: "3"

services:
  database:
    image: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - target: 5432
        published: ${POSTGRES_HOST_PORT}
  redis:
    image: redis
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]
    ports:
      - target: 6379
        published: ${REDIS_HOST_PORT}

volumes:
  db-data:
  redis-data:
